### ISSUE TITLE
[BUG] Crash with GTCEu 2.6.0-beta

### ISSUE THREAD

**Issue by NaCa1814** [brachy84/MechTech#10]
**Versions**
Forge: 14.23.5.2860
GTCEu: 2.6.0-beta

**Crash-Report**
[crash-2023-04-08_18.23.03-client.txt](https://github.com/brachy84/MechTech/files/11183116/crash-2023-04-08_18.23.03-client.txt)

**Comment by magcicada** [comment]
Just need compile the source code with CEu 2.6.0 or later version, that's no need to fix the issue, you can do it yourself.

**Comment by brachy84** [comment]
Compiling yourself is not something most people can do.
